[
  {
    "name": "Paracetamol",
    "category": "Analgesic & Antipyretic",
    "symptoms": ["fever", "headache", "body pain", "toothache"],
    "dosage": "500mg tablet",
    "frequency": "Every 4-6 hours",
    "maxDose": "4000mg per day",
    "usage": "For fever and pain relief",
    "benefits": "Fast-acting pain reliever and fever reducer",
    "schedule": "As needed",
    "timing": "Can be taken any time with or without food",
    "safety": "Safe for most adults. Avoid in liver disease",
    "sources": "Over-the-counter medicine",
    "color": "White",
    "price": "₹20-50"
  },
  {
    "name": "Ibuprofen",
    "category": "NSAID (Anti-inflammatory)",
    "symptoms": ["inflammation", "fever", "arthritis pain", "muscle pain"],
    "dosage": "200-400mg tablet",
    "frequency": "Every 6-8 hours",
    "maxDose": "1200mg per day",
    "usage": "For pain and inflammation",
    "benefits": "Reduces inflammation and relieves moderate pain",
    "schedule": "As needed",
    "timing": "Take with food to prevent stomach upset",
    "safety": "Not for pregnant women or those with kidney disease",
    "sources": "Over-the-counter medicine",
    "color": "Brown",
    "price": "₹30-80"
  },
  {
    "name": "Aspirin",
    "category": "Anti-inflammatory & Blood Thinner",
    "symptoms": ["headache", "chest pain", "heart attack prevention"],
    "dosage": "75-325mg tablet",
    "frequency": "Daily",
    "maxDose": "1000mg per day",
    "usage": "For pain relief and heart health",
    "benefits": "Pain relief and blood clot prevention",
    "schedule": "Regular/Daily",
    "timing": "Morning with water or food",
    "safety": "Not for children under 12 or those allergic to aspirin",
    "sources": "Over-the-counter and prescription",
    "color": "White",
    "price": "₹10-40"
  },
  {
    "name": "Amoxicillin",
    "category": "Antibiotic",
    "symptoms": ["bacterial infection", "throat infection", "ear infection"],
    "dosage": "250-500mg capsule",
    "frequency": "Every 8 hours",
    "maxDose": "3000mg per day",
    "usage": "For bacterial infections",
    "benefits": "Kills harmful bacteria",
    "schedule": "Prescribed by doctor",
    "timing": "Can be taken with or without food",
    "safety": "Check for penicillin allergy before use",
    "sources": "Prescription medicine",
    "color": "Yellow/Orange",
    "price": "₹50-150"
  },
  {
    "name": "Cough Syrup",
    "category": "Antitussive",
    "symptoms": ["dry cough", "wet cough", "cold"],
    "dosage": "5-10ml per dose",
    "frequency": "3-4 times daily",
    "maxDose": "40ml per day",
    "usage": "For cough relief",
    "benefits": "Soothes throat and suppresses cough",
    "schedule": "As needed",
    "timing": "Can be taken anytime",
    "safety": "May cause drowsiness in some people",
    "sources": "Over-the-counter medicine",
    "color": "Brown",
    "price": "₹80-150"
  },
  {
    "name": "Antacid",
    "category": "GI Protectant",
    "symptoms": ["acidity", "heartburn", "indigestion"],
    "dosage": "1-2 tablets",
    "frequency": "2-3 times daily",
    "maxDose": "6 tablets per day",
    "usage": "For stomach acid relief",
    "benefits": "Neutralizes stomach acid quickly",
    "schedule": "As needed",
    "timing": "After meals or as needed",
    "safety": "Generally safe for short-term use",
    "sources": "Over-the-counter medicine",
    "color": "White",
    "price": "₹20-80"
  }
]
